# Generated by Django 4.1.5 on 2023-02-03 09:18

import TemitopePortfolioApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemitopePortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=TemitopePortfolioApp.models.user_image_directory_path)),
            ],
        ),
    ]
