# Generated by Django 4.1.5 on 2023-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemitopePortfolioApp', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
